#
# Module manifest for module 'AzRA'
#
# Generated by: Xtormin (Jennifer Torres)
#
# Generated on: 2025-10-05
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'AzRA.psm1'

# Version number of this module.
ModuleVersion = '1.0.0'

# ID used to uniquely identify this module
GUID = 'a1b2c3d4-e5f6-7890-abcd-ef1234567890'

# Author of this module
Author = 'Xtormin (Jennifer Torres)'

# Copyright statement for this module
Copyright = '(c) Xtormin. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Azure & Microsoft Graph reconnaissance module for security testing and red team operations'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    # Internal reconnaissance - Microsoft Graph / Azure Management API
    'Get-AzRA-Subscriptions',
    'Get-AzRA-ResourcesBySubscriptionID',
    'Get-AzRA-RoleAssignment',
    'Get-AzRA-Users',
    'Get-AzRA-EnterpriseApplications',
    'Get-AzRA-AppRoleAssignment',
    'Get-AzRA-RolesGroupsByEmail',
    'Invoke-AzRA-APIRequest',
    'Request-AzRA-Nonce',
    # Internal reconnaissance - Az module
    'Get-AzRA-DeploymentParameterSecrets',
    # Internal reconnaissance - Automation
    'Get-AzRA-AutomationRunbooks',
    # Internal reconnaissance - Logic Apps
    'Get-AzRA-LogicApps',
    # Internal reconnaissance - Storage
    'Get-AzRA-StorageAccounts',
    # Internal reconnaissance - Key Vault
    'Get-AzRA-KeyVaults',
    # Internal reconnaissance - Virtual Machines
    'Get-AzRA-VirtualMachines',
    # Internal reconnaissance - Entra ID
    'Get-AzRA-EntraID',
    # External reconnaissance
    'Invoke-O365EmailValidator'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('Azure', 'Security', 'Recon', 'RedTeam', 'Pentest', 'Graph', 'REST-API')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/xtormin/AzRA/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/xtormin/AzRA'

        # ReleaseNotes of this module
        ReleaseNotes = 'Initial release - Azure reconnaissance functions'

    } # End of PSData hashtable

} # End of PrivateData hashtable

}